version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: veterinaria_citiaps
  mongo-db:
    image: mongo
    restart: always 
    ports:
      - '27017:27017'

  my-go-app:
    image: driques/my-backend:latest 
    ports:
      - "8000:8000"
    environment:
      - GO_REST_ENV=dev
      - GIN_MODE=debug
      - DB_USER=templategoRESTUser
      - DB_PASS=admin1234
      - DB_DB=templategoREST
      - DB_URL=mongodb:27017
      - DB_URL_SQL=postgres
      - DB_PORT_SQL=5432
      - DB_USER_SQL=postgres
      - DB_PASS_SQL=admin1234
      - DB_DB_SQL=veterinaria_citiaps
      - ADDR=0.0.0.0:8000
      - JWT_KEY=string_largo_unico_por_proyecto
      - CORS_URLS=http://localhost:3000
      - LOG_NAME=template-log
      - FRONT_URL=my-frontend:3000
    depends_on:
      - postgres
      - mongo-db

  my-frontend:
    image: driques/my-frontend-nuxt:latest
    environment:
      HOST: 0.0.0.0
      NUXT_ENV_BACKEND_URL: http://localhost:8000
    ports:
      - "3001:3000"
    depends_on:
      - my-go-app