version: '3.8' 
services:
  db:
    build:
      context: ../Databases/Postgresql
      dockerfile: DockerFile
    image: postgres:latest
    ports:
      - 5434:5432
    env_file:
      - ../Databases/Postgresql/.env
    volumes:
      - postgresql-data:/var/lib/postgresql-data
    container_name: db
    networks:
      - red2
  backend:
    build:
      context: ../Config/Backend/
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: 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
        BRANCH: asalinas-postgresql
    ports: 
      - 3001:3001
    depends_on:
      - db
    env_file:
      - ../Config/Backend/.env
    container_name: backend
    networks:
      - red2
  frontend:
    build:
      context: ../Config/Frontend/ 
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: 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
        BRANCH: asalinas
        BACK_URL: http://backend:3001
        BROWSER_BASE_URL: http://localhost:3001
        HOST: 0.0.0.0
    ports:
      - 3000:3000
    environment:
      - BACK_URL=http://backend:3001
      - HOST=0.0.0.0
      - BROWSER_BASE_URL=http://localhost:3001
    container_name: frontend
    depends_on:
      - backend
    networks:
      - red2
volumes:
  postgresql-data:
networks:
  red2:
    name: red2
