version: '3.8'

services:
  db:
    container_name: postgresql-db
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ../Databases/Postgresql/.env.docker
    volumes:
      - postgresql-data3:/var/lib/postgresql-data3
      - ../Databases/Postgresql/veterinaria_citiaps.sql:/docker-entrypoint-initdb.d/veterinaria_citiaps.sql
    networks:
      - red1
  api:
    container_name: capacitacion-backend-go
    build:
      context: .
      dockerfile: ../Config/Backend/Dockerfile
    ports:
      - 3001:3001
    env_file:
      - ../Config/Backend/.env.docker
    depends_on: db
    networks:
      - red1
  front:
    container_name: capacitacion-frontend-nuxt
    build:
      context: .
      dockerfile: ../Config/Frontend/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ../Config/Frontend/.env.docker
    depends_on: db
    networks:
      - red1
networks:
  red1:
    name: red1
    driver: bridge
volumes:
  postgresql-data3: