version: '3'
services:

  mongo:
    image: mongo
    environment:
        MONGO_INITDB_DATABASE: 'veterinaria_citiaps'
        MONGO_INITDB_ROOT_USERNAME: 'domi'
        MONGO_INITDB_ROOT_PASSWORD: '123456'

    volumes:
      - ./mongo-db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-db/veterinaria_citiaps:/initial/defaultdata:ro
      - ./dbdata/data:/data/db
    networks: 
      - test

  backend:
    image: backend
    networks:
      - test
    depends_on:
      - mongo
    ports:
      - 8080:8080


  frontend:
    image: frontend
    networks:
      - test
    depends_on:
      - backend
    ports:
      - 3000:3000

networks: 
  test:
