version: '2.2'

services:
  db:
    env_file:
      - ../Databases/Postgresql/.env.docker
    container_name: postgresql-db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgresql-data3:/var/lib/postgresql-data3
      - ../Databases/Postgresql/veterinaria_citiaps.sql:/docker-entrypoint-initdb.d/veterinaria_citiaps.sql
    networks:
      - red1
  api:
    container_name: capacitacion-backend-go
    build:
      context: ../Config/Backend
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        BRANCH_BACK: ${BRANCH_BACK}
    env_file:
      - ../Config/Backend/.env.docker
    ports:
      - 3001:3001
    depends_on:
      - db
    volumes:
        - imagenes-data:/app/imagenes
    networks:
      - red1
  front:
    container_name: capacitacion-frontend-nuxt
    build:
      context: ../Config/Frontend
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        BRANCH_FRONT: ${BRANCH_FRONT}
    ports:
      - 3000:3000
    env_file:
      - ../Config/Frontend/.env.docker
    environment:
      - BACK_URL=${BACK_URL}
    depends_on:
      - api
    networks:
      - red1
networks:
  red1:
    name: red1
    driver: bridge
volumes:
  postgresql-data3:
  imagenes-data:
