version: '3.8'

services:
  db:
    build:
      context: ../Databases/Postgresql
      dockerfile: Dockerfile
    image: postgres:latest
    ports:
      - 5433:5432
    env_file:
      - ../Databases/Postgresql/.env
    volumes:
      - postgresql-data:/var/lib/postgresql-data
    networks:
      - red1
  # mongo:
  #   build:
  #     context: ../Databases/Mongodb
  #     dockerfile: Dockerfile
  #   ports:
  #     - 27018:27017
  #   env_file:
  #     - ../Databases/Mongodb/.env
  #   volumes:
  #     - mongodb-data:/data/db
  api:
    build:
      context: ../Config/Backend
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: <GITHUB_TOKEN>
        BRANCH: fmiranda-postgresql
    env_file:
      - ../Config/Backend/.env
    ports:
      - 3001:3001
    depends_on:
      - db
      #  - mongo
    networks:
      - red1
  front:
    build:
      context: ../Config/Frontend
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: <GITHUB_TOKEN>
        BRANCH: fmiranda
    environment:
      - NUXT_HOST=0.0.0.0
      - HOST=0.0.0.0
      - BACK_URL=http://api:3001
      - BROWSER_BASE_URL=http://localhost:3001
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - red1
volumes:
  postgresql-data:
  # mongodb-data:

networks:
  red1:
    name: red1
