version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ../Config/Backend/Dockerfile
    ports:
      - 3001:3001
    env_file:
      - ../Config/Backend/.env.docker
    networks:
      - red1
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: alan
      POSTGRES_PASSWORD: alan
      POSTGRES_DB: veterinaria_citiaps
    ports:
      - 5432:5432
    env_file:
      - ../Databases/Postgresql/.env.docker
    volumes:
      - postgresql-data3:/var/lib/postgresql-data3
    networks:
      - red1
networks:
  red1:
    name: red1
    external: true
volumes:
  postgresql-data3: